/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan;

/**
 *
 * @author ACER
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        mnKonsumen = new javax.swing.JMenuItem();
        mnSupplier = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnTransJual = new javax.swing.JMenuItem();
        mnTransBeli = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnLapPenjualan = new javax.swing.JMenuItem();
        mnLaporanPembelian = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnBackup = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Data Master");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        jMenu3.add(mnBarang);

        mnKonsumen.setText("Data Konsumen");
        mnKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKonsumenActionPerformed(evt);
            }
        });
        jMenu3.add(mnKonsumen);

        mnSupplier.setText("Data Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(mnSupplier);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi");

        mnTransJual.setText("Transaksi Jual");
        mnTransJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransJualActionPerformed(evt);
            }
        });
        jMenu4.add(mnTransJual);

        mnTransBeli.setText("Transaksi Beli");
        mnTransBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransBeliActionPerformed(evt);
            }
        });
        jMenu4.add(mnTransBeli);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Laporan");

        mnLapPenjualan.setText("Laporan Penjualan");
        mnLapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapPenjualanActionPerformed(evt);
            }
        });
        jMenu5.add(mnLapPenjualan);

        mnLaporanPembelian.setText("Laporan Pembelian");
        mnLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanPembelianActionPerformed(evt);
            }
        });
        jMenu5.add(mnLaporanPembelian);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Utility");

        mnBackup.setText("Backup");
        mnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBackupActionPerformed(evt);
            }
        });
        jMenu6.add(mnBackup);

        jMenuBar1.add(jMenu6);

        mnKeluar.setText("Keluar");
        mnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnKeluarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        new FormBarang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKonsumenActionPerformed
        new FormKonsumen().setVisible(true);
    }//GEN-LAST:event_mnKonsumenActionPerformed

    private void mnTransJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransJualActionPerformed
        new FormTransaksi().setVisible(true);
    }//GEN-LAST:event_mnTransJualActionPerformed

    private void mnTransBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransBeliActionPerformed
        new FormTransaksiPembelian().setVisible(true);
    }//GEN-LAST:event_mnTransBeliActionPerformed

    private void mnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKeluarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnKeluarMouseClicked

    private void mnLapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapPenjualanActionPerformed
       new LapPenjualan().setVisible(true);
    }//GEN-LAST:event_mnLapPenjualanActionPerformed

    private void mnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBackupActionPerformed
        new FormBackup().setVisible(true);
    }//GEN-LAST:event_mnBackupActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        new FormSupplier().setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanPembelianActionPerformed
        new LapPembelian().setVisible(true);
    }//GEN-LAST:event_mnLaporanPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnBackup;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenu mnKeluar;
    private javax.swing.JMenuItem mnKonsumen;
    private javax.swing.JMenuItem mnLapPenjualan;
    private javax.swing.JMenuItem mnLaporanPembelian;
    private javax.swing.JMenuItem mnSupplier;
    private javax.swing.JMenuItem mnTransBeli;
    private javax.swing.JMenuItem mnTransJual;
    // End of variables declaration//GEN-END:variables
}
